# server:
#    port: 8900

spring:
   main:
      allow-bean-definition-overriding: true
      application:
         name: colors-service
#       datasource:
#          url:
#          driverClassName:
#          username:
#          password:
      jpa:
         show-sql: true
